@api = http://localhost:1000/contacts

### Getting all contacts
GET {{api}}

### Creating contact
POST {{api}}
Content-Type: application/json

{
    "name": "Marian",
    "phone": "1111-1111"
}

### Getting a product by id
GET {{api}}/5

### Deleting a product by id
DELETE {{api}}/5

### Get total product
GET {{api}}/count

### Update a product
PUT {{api}}/5
Content-Type: application/json

{
    "name": "Lilian5",
    "phone": "1111-1111"
}